{% set version = "23.3.0" %}

package:
  name: monkeytype
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/m/monkeytype/MonkeyType-{{ version }}.tar.gz
    sha256: f2595db34d57cdddbde5a990117a50a22f373dbb917a2a0fa91ffbe07dfe0313
  - folder: src
    url: https://github.com/Instagram/monkeytype/archive/v{{ version }}.tar.gz
    sha256: c39656d9c1c2f43e7b0d0822ab1ef80ffa111f1a48d1e9886fd7a949b27e47f8

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - monkeytype = monkeytype.cli:entry_point_main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - libcst >=0.4.4
    - mypy_extensions
    - python >=3.7

test:
  source_files:
    - src/tests
  requires:
    - {{ compiler('c') }}
    - cython
    - django
    - pip
    - pytest
    - pytest-cov
  imports:
    - monkeytype
  commands:
    - python -m pip check
    - monkeytype --help
    - cd src && pytest -vv -k "not test_includes_otherwise" --cov=monkeytype --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100

about:
  home: https://github.com/Instagram/MonkeyType
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Generating type annotations from sampled production types
  doc_url: https://monkeytype.readthedocs.io
  doc_source_url: https://github.com/Instagram/MonkeyType/tree/master/doc
  description: |
    MonkeyType collects runtime types of function arguments and return values,
    and can automatically generate stub files or even add draft type
    annotations directly to your Python code based on the types collected at
    runtime.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
