{% set name = "MonkeyType" %}
{% set version = "18.5.1" %}
{% set sha256 = "e170d1224eec57ffb0c66293eb55cab30e4acb116e5771c40b31ed0399878bcf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - monkeytype=monkeytype.cli:entry_point_main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - retype

test:
  requires:
    - cython
    - django
    - git
    - pytest-smartcov
  imports:
    - monkeytype
  commands:
    - monkeytype --help
    # TODO: make upstream PR for redistributing tests
    - git clone https://github.com/Instagram/MonkeyType
    - cd MonkeyType
    - git checkout v{{ PKG_VERSION }}
    - rm -rf monkeytype  # [not win]
    - rd /s /q monkeytype  # [win]
    - del pytest.ini  # [win]
    # FIXME: not sure about this one
    - python -m pytest -k "not print_stub_ignore_existing_annotations and not display_list_of_modules and not includes_otherwise and not pathlike_parameter and not get_diff and not retype_failure and not no_traces and not display_sample_count_from_cli and not retype_failure and not generate_stub and not apply_stub_init"  # [win]



about:
  home: https://github.com/Instagram/MonkeyType
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Generating type annotations from sampled production types

  description: |
    MonkeyType collects runtime types of function arguments and return values,
    and can automatically generate stub files or even add draft type
    annotations directly to your Python code based on the types collected at
    runtime.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
